config/routes.rb
Lasvea::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "pages#index"

  get "/catalogue", to: "pages#catalogue", as: :catalogue
  get "/catalogue/:id/products", to: "catalogues#show", as: :catalogue_show
  get "/products/:id", to: "products#show", as: :product
  get "/about", to: "pages#about", as: :about

  resources :contact_infos, only: [:new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  has_attached_file :banner, styles: { thumb: "50x50",
                                        medium: "#250x150",
                                        large: "450x300" },
                              default_url: "http://placehold.it/350x250"
  validates_attachment_content_type :banner, content_type: %w(image/jpeg image/jpg image/png)

  validates :name, presence: true
  validates :description, presence: true
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :content, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  has_attached_file :picture, styles: { thumb: "50x50",
                                        medium: "250x150",
                                        large: "450x300" },
                              default_url: "http://placehold.it/250x150"
  validates_attachment_content_type :picture, content_type: %w(image/jpeg image/jpg image/png)

  validates :pname, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true
  validates :price_local, presence: true
  validates :price_international, presence: true
  validates :category, presence: true
  validates :picture, presence: true

  def to_s
    "#{pname} (#{code})"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  def new
    @contact_info = ContactInfo.new
  end

  def create
    @contact_info = ContactInfo.new(post_params)
    ContactMailer.contact_information(@contact_info).deliver

    flash[:success] = "Thank you for contacting Sugar Plum Global distributors! We'll get back to you shortly."
    redirect_to root_path
  end

  def post_params
    params.require(:contact_info).permit!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @products = Product.where(is_featured: true).last(4)
  end

  def catalogue
    @categories = Category.all
  end

  def about

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  layout "blank"

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/catalogues/show.html.erb
<div class="row cat">
  <div class="col-md-12 cat-name">
    <h1><%= @category.name %></h1>
    <hr>
</div>
<div class="row welcome">
  <div class="col-md-12">
    <%= image_tag @category.banner.url, size: "930x350"%>
    <p style="padding-left: 20px; padding-top: 20px;"><%= @category.description %></p>
    <hr>
  </div>
</div>
</div>
<% @products.each_slice(4) do |products| %>
  <div class="row">
    <% products.each do |product|%>
      <%= link_to(product_path(product.id)) do %>
        <div class="col-md-3">
          <%= render partial: "products/preview", locals: { product: product } %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/contact_infos/new.html.erb
<div class="row">
  <div class="col-md-7 contact">
    <%= simple_form_for(@contact_info, method: :post, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }) do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :contact_number, label: "Country" %>
      <%= f.input :content, as: :text %>
      <%= f.submit "Send", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-md-5 postit">
  <div class=""><b>E-mail:</b> <br>sales@sugarplumglobal.com </div> <br>
  <div class=""><b>Address:</b><br> 3 Tanguile Street, Monte Vista Subdivision Marikina City, Philippines</div>
  <br>
  <p>
    Upon sending us an inquiry, you will be
    given a user account which you can use to
    view our catalogue with prices and details
    on how to order.
  </p>
   <%= image_tag ("cup.png") %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sugar Plum Global Distributors, Inc.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Duru+Sans' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet" type="text/css">

  <script type="text/javascript">var switchTo5x=true;</script>
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "1059b8ca-c7b4-4779-b637-d324d213f655", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  <script type="text/javascript">
  $(document).ready(function() {
    $(".product-image").magnificPopup({
      delegate: 'a',
      type: 'image'
    });
  });
  </script>


  <link href='http://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render partial: "shared/header" %>
<div class="container" id="content">
  <%= render partial: "shared/notification" %>
  <%= yield %>
</div>


</body>
<%= render partial: "shared/footer" %>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lasvea</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Duru+Sans' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet" type="text/css">

  <script type="text/javascript">var switchTo5x=true;</script>
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "1059b8ca-c7b4-4779-b637-d324d213f655", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>

</html>

app/views/pages/about.html.erb
<div class="row">
<div class="col-md-6 about">
  <h1>About Us</h1>
  <hr>
  <p>
  Sugar Plum Global Distributors, Inc. (formerly La Svea, Inc.) is a family-owned corporation that started in
  2009 with the intention of providing inspiration to bakers around the globe. The company supplies Royal
  Icing products to both the local and international markets.</p>
  <p>
  Five-star hotels are our primary customers in the local market, for which we provide customized Royal Icing
  decorations for special functions and holiday celebrations. We export our products to companies in the
  United States, Australia and New Zealand.</p>
  <p>
  Our products are 100% hand crafted and all done under close supervision. We make sure that we comply
  with all the requirements of every country we ship them to. We package our products according to the
  specifications of each client and customize our packaging depending on their needs. We do retail (store-
  ready) as well as wholesale packaging. Most importantly, our prices, as well as our products, are very
  competitive.</p>
  <p>
  We always do our best to focus on the quality, good service, meeting customers' expectations and
  everything that spells excellence.</p>
</div>

<div class="col-md-6 cupcake">
<%= image_tag ("cupcake.jpg") %>
<%= image_tag ("cupcake2.jpg") %>
<%= image_tag ("cupcake3.jpg") %>
<%= image_tag ("cupcake4.jpg") %>
<%= image_tag ("cupcake5.jpg") %>
<%= image_tag ("cupcake6.jpg") %>
<%= image_tag ("cupcake7.jpg") %>
<%= image_tag ("cupcake8.jpg") %>
<%= image_tag ("cupcake9.jpg") %>
<%= image_tag ("cupcake10.jpg") %>
<%= image_tag ("cupcake11.jpg") %>
<%= image_tag ("cupcake12.jpg") %>
</div>
</div>

app/views/pages/catalogue.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="title">Catalogue</h1>
    <hr>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p>
    We call our products edible art – fun, whimsical Royal Icing decorations and toppers for cakes, cupcakes and cookies. From home bakers to professional
    pastry chefs, our wide selection of products are designed and artfully crafted to inspire and make anyone's pastry decorating for any occasion more fun!
    Can’t find what you need? Contact us and inquire about customized products.</p>
    <p>
    You must be logged in to see the prices of the products. Go to our contact page to create a user account for free.
    </p>
  </div>
</div>

<% @categories.each_slice(2) do |slice| %>
  <div class="row">
    <% slice.each do |category| %>
      <div class="col-md-6 preview_cat">
        <%= image_tag(category.banner.url(:medium), size: "350x250") %>
        <p class="description content">
          <%= link_to category.name, catalogue_show_path(category.id) %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-md-7 contact">
    <%= simple_form_for(:contact_info, url: "/contact_post", method: :post, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } }) do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :contact_number, label: "Country" %>
      <%= f.input :message, as: :text %>
      <%= f.submit "Send", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-md-5 postit">
  <div class=""><b>E-mail:</b> <br>sales@sugarplumglobal.com </div> <br>
  <div class=""><b>Address:</b><br> 3 Tanguile Street, Monte Vista Subdivision Marikina City, Philippines</div>
  <br>
  <p>
    Upon sending us an inquiry, you will be
    given a user account which you can use to
    view our catalogue with prices and details
    on how to order.
  </p>
   <%= image_tag ("cup.png") %>
</div>
</div>

app/views/pages/index.html.erb
<div class="row"> 
  <div class="col-md-12">
    <%= render partial: "shared/carousel" %>
  </div>
</div>
<div id="featured">
  <%= render partial: "shared/preview" %>
</div>
<div class="row content-cupcakes">
  <div class="col-md-12">
    <%= render partial: "shared/lasvea" %>
  </div>
</div>

app/views/products/_preview.html.erb
<div class="product">
  <div class="product-image">
    <%= link_to(image_tag(product.picture.url(:medium)), product.picture.url(:large)) %>
  </div>
  <div class="product-name">
    <%= "#{product.pname} (#{product.code})" %>
  </div>
  <% if user_signed_in? %>
    <div class="product-pricing row">
      <% if !current_user.is_international %>
        <div class="col-md-6 local">
          Php <%= product.price_local %> 
        </div>
      <% else %>
        <div class="col-md-6 international">
          $ <%= product.price_international %> 
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row product">
  <div class="col-md-4">
    <div class="product-image">
      <%= image_tag @product.picture.url(:medium) %>
    </div>
    <div class="product-name">
      <%= @product.pname %>
    </div>
  </div>

  <div class="col-md-8">
    <h1><%= @product.pname %></h1>
    <hr>
    <div class="product-description">
      <%= @product.description %>
    </div>
    <div class="product-pricing">
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "Miscellaneous_1.JPG" %> 
     
    </div>
      <div class="item">
      <%= image_tag "Easter.JPG" %> 
    
    </div>
    <div class="item">
      
      <%= image_tag "Animal.JPG" %> 
    </div>
    <div class="item">
      <%= image_tag "Christmas.JPG" %> 
    
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="row">
  <div class="col-md-12 reserved">©Sugar Plum Global Dist., Inc. Copyright 2014. All Rights Reserved.<br>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Catalogue", catalogue_path %></li>
      <li><%= link_to "About", "" %></li>
      <li><%= link_to "Contact", "" %></li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header"> 
  <div class="container">
    <div class="row header-inner">
      <div class="col-md-3 left">
        <%= link_to image_tag("logo.png"), root_path %>
      </div>
      <div class="col-md-9 nav">
        <%= render partial: "shared/navigation" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_lasvea.html.erb
<div class="row welcome">
  <div class="col-md-12">
    <h1>Welcome to Sugar Plum, a leading manufacturer of Royal Icing in the Philippines</h1>
    <hr>
    <p>
    If you’re looking for the perfect decorations to top your cakes, cupcakes and cookies, Royal Icing is the product for you!
    </p>
    <p>
    The master culinary artisans here at Sugar Plum provide you with edible art that will spruce up any sweet treat. Whether it’s for Christmas, Valentines, Halloween or graduation day, we have the royal solution for every occasion. Browse our catalog to see the products we offer. Can’t find what you need? Contact us and inquire about customized products.
    </p>
    <p>
    We do retail (store-ready) as well as wholesale packaging. Local and international orders are accepted. For business inquiries, email us at <a href="emailto:sales@sugarplumglobal.com.">sales@sugarplumglobal.com</a>.
    </p>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div id="navigation">
  <div class="col-md-12">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Catalogue", catalogue_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_contact_info_path %></li>
      <% if user_signed_in? %>
        <li>
        <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } do %>
          Customer Logout
        <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_session_path do %>
            Customer Login
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notification.html.erb
<% flash.each do |key, value| %>
  <div id="notice" class="bs-callout bs-callout-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_preview.html.erb
<div class="row" id="featured-products">
  <div class="col-md-12">
    <h1 class="title">Featured Products</h1> 
    <hr>
  </div>
  <div class="col-md-12">
  </div>
  <% @products.each_slice(4) do |products| %>
    <div class="row">
      <% products.each do |product|%>
        <div class="col-md-3">
          <%= render partial: "products/preview", locals: { product: product } %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>